import { Directions, PlayerStatus, MapStore, PlayerStore } from "../Types";
export declare class Player {
    private initialPos;
    private location;
    private velocity;
    private speed;
    private currentDirection;
    private nextDirection;
    private mostRecentUpdate;
    private mapStore;
    private playerStore;
    id: string;
    constructor(initX: number, initY: number, id: string, mapStore: MapStore, playerStore: PlayerStore);
    receiveInput(dir: Directions): void;
    updateState: () => void;
    getCurrentState: () => PlayerStatus;
    private moveTowardsTarget;
    isCentered: () => true | undefined;
    private targetLocation;
    private canMoveRight;
    private canMoveLeft;
    private canMoveUp;
    private canMoveDown;
    private notMoving;
    private currentCellType;
    private targetCellType;
    private currentCell;
    private targetCell;
    private getCellType;
    private toLocationCoords;
    private toGridCoords;
}
