import { AnyAction, Dispatch } from "redux";
import { PlayerStatus } from "..";
import { StampedInput } from "../Types";
import { PlayerState, PlayerStateAction } from "../Types/ReduxTypes";
export declare const playerStateReducer: (state: PlayerState | undefined, action: PlayerStateAction) => PlayerState;
export declare const updatePlayerStatus: (playerId: string, newStatus: PlayerStatus) => (dispatch: Dispatch<AnyAction>) => void;
export declare const addPlayerInput: (playerId: string, input: StampedInput) => (dispatch: Dispatch<AnyAction>) => void;
export declare const addPlayer: (playerId: string) => (dispatch: Dispatch<AnyAction>) => void;
export declare const removePlayer: (playerId: string) => (dispatch: Dispatch<AnyAction>) => void;
export declare const setCurrentPlayers: (currentPlayerId: string, fullPlayerList: string[]) => (dispatch: Dispatch<AnyAction>) => void;
